### ISSUE TITLE
Bug in `find_motifs`

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#203]
When running `find_motifs` I'm getting the following repeatedly printing:

```
thread '<unnamed>' panicked at src/find_motifs/mod.rs:4451:41:
called `Option::unwrap()` on a `None` value
```

**Comment by ArtRand** [comment]
@Ge0rges sorry about that. 

Just a check, can you avoid the crash if you pass the `--skip-search` flag? Any chance you can share the dataset that's producing the error?

**Comment by Ge0rges** [comment]
@ArtRand adding `--skip-search` did fix the issue. I'm working on trying to get you a smaller dataset that crashes.

**Comment by ArtRand** [comment]
@Ge0rges that's be excellent. 

I'm pretty sure I know where the bug is, but always easier to test against a dataset that exposes the bug than to ping-pong builds. If you can't get anything small enough, email me art.rand[at]nanoporetech.com and I'll share a link (if that's OK with you).

**Comment by Ge0rges** [comment]
Email sent.

**Comment by ArtRand** [comment]
I sent a link, let me know if you have any problems uploading a dataset.

**Comment by Ge0rges** [comment]
File just finished uploading.

**Comment by wangziyuan66** [comment]
I still get the bug. When I  use --context-size 4 4 --threads 32 --skip-search, it will show

"thread '<unnamed>' panicked at src/find_motifs/mod.rs:1294:13:
log-odds per base should not be empty
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
